[0m13:45:48.463405 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001813DBFD890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001813D9B7A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001813D4A67D0>]}


============================== 13:45:48.467412 | 080aa687-e9bf-47e0-9b51-2cd1e020ef1d ==============================
[0m13:45:48.467412 [info ] [MainThread]: Running with dbt=1.6.2
[0m13:45:48.468404 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\VREDDY\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m13:46:04.910652 [debug] [MainThread]: Starter project path: C:\Users\VREDDY\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m13:46:04.962637 [info ] [MainThread]: 
Your new dbt project "pmt_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:46:04.963648 [info ] [MainThread]: Setting up your profile.
[0m13:46:15.758932 [debug] [MainThread]: Command `dbt init` succeeded at 13:46:15.758932 after 27.32 seconds
[0m13:46:15.758932 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001813D4B18D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001813D570390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001813D49E050>]}
[0m13:46:15.759950 [debug] [MainThread]: Flushing usage events
[0m14:37:37.560373 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209754E9610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020975198310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020974D97150>]}


============================== 14:37:37.564380 | a5264c3f-486c-42e9-be6b-2ac0a72f5e49 ==============================
[0m14:37:37.564380 [info ] [MainThread]: Running with dbt=1.6.2
[0m14:37:37.564380 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\VREDDY\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt snapshot --select fact_permits', 'send_anonymous_usage_stats': 'True'}
[0m14:37:37.565373 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\VREDDY\Softwares\nr-dap-dlh\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:37:37.566372 [debug] [MainThread]: Command `dbt snapshot` failed at 14:37:37.566372 after 0.04 seconds
[0m14:37:37.566372 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020975061610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209750B5350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020974D8EF10>]}
[0m14:37:37.566372 [debug] [MainThread]: Flushing usage events
